# -*- coding: utf-8 -*-
"""DAV PROJECT_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Olu5SUsPZp29AFsWQfpSOPS0_Z_QqCbi
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/restaurants.csv')
df

df.head(5)

df.info

df.describe()

df.shape

df.columns

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

#CITY COUNT
df['City'].value_counts()

# top 5 restaurants with highest ratings
df1 = df['Rating'].value_counts().sort_values(ascending=False).head(5)
df1

df2 = df['Rating'].max()
df2

df3 = df.loc[df['Rating'] ==  df2]
df3

df1.plot(kind="bar")
plt.title("The Top Ten Rating")
plt.xlabel("Rating")
plt.ylabel('Count')
plt.show()

#distribution of restaurants across cities
plt.figure(figsize=(15,8))
sns.countplot(y = 'City', data = df, order = df['City'].value_counts().index, palette = 'viridis')
plt.title('Distribution of Restaurants across Cities in India')
plt.xlabel('Number of Restaurants')
plt.ylabel('City')
plt.show()

#voting distribution
plt.figure(figsize=(8,6))
plt.hist(df['Votes'], color='orange')
plt.title('Distribution of Restaurant Votes in India')
plt.xlabel('Votes')
plt.ylabel('Count')
plt.show()

"""TOP CUISINS IN INDIA"""

#GROUPING THE DATA BY CITY AND CUISINE AND COUNTING THE RESTAURANTS

df_cuisine = df.groupby(['City','Cuisine'])['Name'].count().reset_index()
df_cuisine

#TOP CUISINES FOR EACH CITY
df_top_cuisine = df_cuisine.loc[df_cuisine.groupby('City')['Name'].idxmax()]
df_top_cuisine

plt.figure(figsize=(22,12))
plt.bar(df_top_cuisine['City'], df_top_cuisine['Cuisine'], color='blue')
plt.title('Top cuisines for each city', fontsize=18)
plt.xlabel('city')
plt.ylabel('Number of restaurants')

plt.show()

"""COMPARISON OF AVERAGE RATINGS ACROSS CITIES"""

#create a dataframe with average rating by city
df_rating = df.groupby('City')['Rating'].mean().reset_index()
df_rating

#sorting the dataframe by rating
df_rating = df_rating.sort_values('Rating').reset_index()
df_rating

#pie chart
plt.figure(figsize=(8,8))
plt.pie(df_rating['Rating'], labels=df_rating['City'], autopct='%1.1f%%', explode=[0.1]*len(df_rating))
plt.title('Comparison of Average Ratings Across city')
plt.show()

"""COMPARISON OF AVERAGE DINING COST ACROSS CITES"""

#creating a dataframe with avg cost and city
df_cost_city = df.groupby('City')['Cost'].mean().reset_index()
df_cost_city

#sorting the dataframe by cost
df_cost_city = df_cost_city.sort_values('Cost').reset_index()
df_cost_city

#plotting the horizontal  bar graph for the comparison of avg cost with cities
plt.figure(figsize=(12,8))
plt.barh(df_cost_city['City'], df_cost_city['Cost'], color='#FFC107')
plt.title('comparison of average cost across cities', fontsize=18)
plt.xlabel('Average cost')
plt.ylabel('City')
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.show()